name: Update gist with WakaTime stats
on:
  push:
    branches: master
    
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node update-waka.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 82bf215f73cc88c6563f405d2d3d7845
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}