name: Waka Readme

on:
  schedule:
    - cron: '35 21 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: zh
          SHOW_LINES_OF_CODE: "True" # 显示截至日期写入的代码行数
          SHOW_LOC_CHART: "False" # 年份不同季度编写的代码行数
          SHOW_SHORT_INFO: "False" # 用户的简短趣闻信息
